### ISSUE TITLE
Clamping Inside Quantization Function

### ISSUE THREAD

**Issue by Ahmed-Mujtaba-98** [mrusci/training-mixed-precision-quantized-networks#1]
Hi, 
The asymmetric quantization function used in the code is not clamping the data tensor for which the values exceed the specified bit width. For 4-bit quantization, the deployment model contains values (weights) that exceed the 4-bit range. 
Is there any problem if I clamp the data tensor before converting it back to floating-point on the accuracy?
If it is, then what could be the solution?

Thanks

**Comment by mrusci** [comment]
The tensor is not clamped because min/max stats are used to derive the quantization range for the weights: tensors will always be between min and max value. 
The quantized values (e.g. 4 bit) looks unbounded but can only assumes 2^4 values. If W_q is a quantized values, it holds the formula W_q = Z_wq + W, where Z_wq is a fixed integer zero point (we used 16 bit for it - more details in the paper) and W is an unsigned 4-bit values in the range [0, .. 2^4 -1]. Further deployment details can be found also in this paper https://ieeexplore.ieee.org/document/9049084 and related code.
If you are interested in forcing also Z_w to be bounded to 4 bit, you need to clamp the quantization stats to include the real zero point. e.g. w_max = max (w_max, 0). This additional constraint may lead to accuracy degradation but I do not expect to be significant.

**Comment by Ahmed-Mujtaba-98** [comment]
Thanks for the comment and solution.
